import { StyleSheet } from 'react-native';

const PRIMARY_BLUE = '#045fb5';

export const styles = StyleSheet.create({
  container: {
    padding: 20,
    backgroundColor: '#fff',
    flexGrow: 1,
    paddingBottom: 40,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 18,
    marginTop: 32,
  },
  headerTitle: {
    fontSize: 36,
    fontWeight: 'bold',
    color: '#222',
    flex: 1,
    textAlign: 'left',
    letterSpacing: 0.2,
    lineHeight: 44,
  },
  headerIcons: {
    flexDirection: 'row',
    alignItems: 'center',
    marginLeft: 12,
  },
  headerProfileIcon: {
    fontSize: 28,
    color: '#1976d2',
    marginLeft: 8,
  },
  subtitle: {
    fontSize: 28,
    fontWeight: 'bold',
    color: '#222',
    marginBottom: 8,
    marginTop: 2,
    letterSpacing: 0.1,
    lineHeight: 34,
  },
  description: {
    fontSize: 16,
    color: '#666',
    marginBottom: 22,
    lineHeight: 22,
    letterSpacing: 0.1,
  },
  sectionCard: {
    backgroundColor: '#fff',
    borderRadius: 16,
    padding: 18,
    borderWidth: 1,
    borderColor: '#ececec',
    marginBottom: 20,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.04,
    shadowRadius: 8,
    elevation: 1,
  },
  sectionHighlight: {
    backgroundColor: PRIMARY_BLUE,
    borderColor: PRIMARY_BLUE,
    shadowColor: PRIMARY_BLUE,
  },
  sectionHighlightText: {
    color: '#fff',
    fontWeight: 'bold',
    fontSize: 26,
    marginBottom: 4,
    lineHeight: 32,
  },
  sectionHighlightSub: {
    color: '#e6eaff',
    fontSize: 19,
    marginBottom: 0,
    lineHeight: 24,
  },
  sectionIconCircle: {
    width: 38,
    height: 38,
    borderRadius: 19,
    backgroundColor: '#e6eaff',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 10,
  },
  sectionIcon: {
    fontSize: 20,
    color: PRIMARY_BLUE,
  },
  sectionTitle: {
    fontSize: 24,
    fontWeight: 'bold',
    color: '#222',
    marginBottom: 6,
    letterSpacing: 0.1,
    lineHeight: 30,
  },
  sectionText: {
    fontSize: 16,
    color: '#444',
    marginBottom: 8,
    lineHeight: 22,
  },
  sectionImage: {
    width: '100%',
    height: 240,
    borderRadius: 10,
    marginBottom: 10,
    backgroundColor: '#f0f0f0',
  },
  ctaButton: {
    backgroundColor: PRIMARY_BLUE,
    borderRadius: 22,
    paddingVertical: 14,
    alignItems: 'center',
    marginTop: 10,
    width: '100%',
    alignSelf: 'center',
    shadowColor: PRIMARY_BLUE,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 8,
    elevation: 2,
  },
  ctaButtonText: {
    color: '#fff',
    fontWeight: 'bold',
    fontSize: 20,
    letterSpacing: 0.2,
  },
}); 